image: node:14.12.0

# workflow:
#   rules:
#     - if: '$CI_COMMIT_BRANCH'

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules

install_dependencies:
  stage: build
  script:
    - cd client
    - npm install
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  script:
    - cd client
    - npm test
  artifacts:
    paths:
      - test_reports/
#   rules:
#     - if: '$CI_COMMIT_BRANCH != "master"'

deploy_doc_tracer:
  stage: deploy
  script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh root@cmpt371.persea.ca "cd requirements-traceability/backend && git pull origin master && npm install; exit"
  environment:
    name: doc_tracer
    url: cmpt371.persea.ca
    on_stop: stop_app
  only:
    - master

stop_app:
  stage: deploy
  script:
    - echo "stop text"
  when: manual
  environment:
    name: doc_tracer
    url: cmpt371.persea.ca
    action: stop
