image: node:14.12.0

stages:
  - build
#  - confidence-check
  - test
  - deploy

cache:
  paths:
    - client/node_modules

install_dependencies:
  stage: build
  script:
    - cd client
    - npm install
#    - npm run start
  artifacts:
    paths:
      - node_modules/

#e2e:firefox:
#  stage: confidence-check
#  services:
#    - selenium/standalone-firefox
#  script:
#    - npm run confidence-check --host=selenium__standalone-firefox

#e2e:chrome:
#  stage: confidence-check
#  services:
#    - selenium/standalone-chrome
#  script:
#    - npm run confidence-check --host=selenium__standalone-chrome

run_tests:
  stage: test
  script:
    - cd client
    - npm test --ci
  artifacts:
    paths:
      - test_reports/

deploy_doc_tracer:
  stage: deploy
  script:
    # setup ssh
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # deploy updates
    - ssh root@cmpt371.persea.ca "cd requirements-traceability/backend && git pull origin master && npm install && cd ../client && npm install"
    - ssh root@cmpt371.persea.ca "cd requirements-traceability && pm2 startOrRestart ecosystem.config.yml"
  environment:
    name: doc_tracer
    url: cmpt371.persea.ca
  only:
    - master

