image: node:14.12.0

# workflow:
#   rules:
#     - if: '$CI_COMMIT_BRANCH'

stages:
  - build
#  - confidence-check
  - test

cache:
  paths:
    - client/node_modules

install_dependencies:
  stage: build
  script:
    - cd client
    - npm install
#    - npm run start
  artifacts:
    paths:
      - node_modules/

#e2e:firefox:
#  stage: confidence-check
#  services:
#    - selenium/standalone-firefox
#  script:
#    - npm run confidence-check --host=selenium__standalone-firefox
    
#e2e:chrome:
#  stage: confidence-check
#  services:
#    - selenium/standalone-chrome
#  script:
#    - npm run confidence-check --host=selenium__standalone-chrome

run_tests:
  stage: test
  script:
    - cd client
    - npm test --ci
  artifacts:
    paths:
      - test_reports/
#   rules:
#     - if: '$CI_COMMIT_BRANCH != "master"'

