export const CREATE_DOC_START = 'CREATE_DOC_START';

export const CREATE_DOC_FAILURE = 'CREATE_DOC_FAILURE';

export const CREATE_DOC_SUCCESS = 'CREATE_DOC_SUCCESS';

export const DELETE_DOC_START = 'DELETE_DOC_START';

export const DELETE_DOC_FAILURE = 'DELETE_DOC_FAILURE';

export const DELETE_DOC_SUCCESS = 'DELETE_DOC_SUCCESS';




