export const UPDATE_REQ_NAME_START = 'UPDATE_REQ_NAME_START';

export const UPDATE_REQ_NAME_FAILURE = 'UPDATE_REQ__NAME_FAILURE';

export const UPDATE_REQ_NAME_SUCCESS = 'UPDATE_REQ_NAME_SUCCESS';




