// actions for getting user
export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE'

// actions for getting user recent docs
export const FETCH_USER_RECENT_DOCS_START = 'FETCH_USER_RECENT_DOCS_START'
export const FETCH_USER_RECENT_DOCS_SUCCESS = 'FETCH_USER_RECENT_DOCS_SUCCESS'
export const FETCH_USER_RECENT_DOCS_FAILURE = 'FETCH_USER_RECENT_DOCS_FAILURE'
