// actions for getting user
export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE'

// actions for getting user recent docs
export const FETCH_USER_RECENT_DOCS_START = 'FETCH_USER_RECENT_DOCS_START'
export const FETCH_USER_RECENT_DOCS_SUCCESS = 'FETCH_USER_RECENT_DOCS_SUCCESS'
export const FETCH_USER_RECENT_DOCS_FAILURE = 'FETCH_USER_RECENT_DOCS_FAILURE'

// actions for getting user recent docs
export const UPDATE_USER_RECENT_DOCS_START = 'UPDATE_USER_RECENT_DOCS_START'
export const UPDATE_USER_RECENT_DOCS_SUCCESS = 'UPDATE_USER_RECENT_DOCS_SUCCESS'
export const UPDATE_USER_RECENT_DOCS_FAILURE = 'UPDATE_USER_RECENT_DOCS_FAILURE'

// actions for getting user recent docs
export const FETCH_USER_NOTIFICATIONS_START = 'FETCH_USER_NOTIFICATIONS_START'
export const FETCH_USER_NOTIFICATIONS_SUCCESS =
  'FETCH_USER_NOTIFICATIONS_SUCCESS'
export const FETCH_USER_NOTIFICATIONS_FAILURE =
  'FETCH_USER_NOTIFICATIONS_FAILURE'

// actions for getting user notifications
export const UPDATE_USER_NOTIFICATIONS_START = 'UPDATE_USER_NOTIFICATIONS_START'
export const UPDATE_USER_NOTIFICATIONS_SUCCESS =
  'UPDATE_USER_NOTIFICATIONS_SUCCESS'
export const UPDATE_USER_NOTIFICATIONS_FAILURE =
  'UPDATE_USER_NOTIFICATIONS_FAILURE'
