export const SET_LOGGEDIN = 'SET_LOGGEDIN';

export const UPDATE_TREEDATA = 'UPDATE_TREEDATA';

export const UPDATE_SELECTEDNODEID = 'UPDATE_SELECTEDNODEID';

export const SET_MODALOBJECT = 'SET_MODALOBJECT';

export const SET_SELECTED_DOCUMENTPANEL_ID = 'SET_SELECTED_DOCUMENTPANEL_ID';