export const CREATE_DOC_START = 'CREATE_DOC_START'

export const CREATE_DOC_FAILURE = 'CREATE_DOC_FAILURE'

export const CREATE_DOC_SUCCESS = 'CREATE_DOC_SUCCESS'

export const DELETE_DOC_START = 'DELETE_DOC_START'

export const DELETE_DOC_FAILURE = 'DELETE_DOC_FAILURE'

export const DELETE_DOC_SUCCESS = 'DELETE_DOC_SUCCESS'

// actions for getting user docs
export const FETCH_USER_DOCS_START = 'FETCH_USER_DOCS_START'
export const FETCH_USER_DOCS_SUCCESS = 'FETCH_USER_DOCS_SUCCESS'
export const FETCH_USER_DOCS_FAILURE = 'FETCH_USER_DOCS_FAILURE'

export const UPDATE_CURRENT_DOCUMENT = 'UPDATE_CURRENT_DOCUMENT'