const userActionTypes = {
  FETCH_USER_INFO_START: "FETCH_USER_INFO_START",
  FETCH_USER_INFO_SUCCESS: "FETCH_USER_INFO_SUCCESS",
  FETCH_USER_INFO_FAILURE: "FETCH_USER_INFO_FAILURE",

  USER_CREATION_START: "USER_CREATION_START",
  USER_CREATION_SUCCESS: "USER_CREATION_START",
  USER_CREATION_FAILURE: "USER_CREATION_START",
};

export default userActionTypes;
